# fly.toml app configuration file for FastAPI application
app = "fastapi-book-project"  # Use a meaningful app name
primary_region = "lhr"  # Set the primary region (London)

[build]
  # Specify the Dockerfile location if it's not in the root directory
  # dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000  # Internal port for FastAPI
  force_https = true  # Redirect HTTP to HTTPS
  auto_stop_machines = true  # Stop machines when not in use to save costs
  auto_start_machines = true  # Start machines when traffic is detected
  min_machines_running = 0  # No machines running when idle
  processes = ["app"]  # Process group name

[[vm]]
  memory = "1gb"  # 1GB of memory
  cpu_kind = "shared"  # Shared CPU
  cpus = 1  # 1 CPU core
  memory_mb = 1024  # Same as memory above (redundant, can be removed)

[[services]]
  internal_port = 8000  # Match the internal port for FastAPI
  protocol = "tcp"  # TCP protocol for HTTP

  [[services.ports]]
    handlers = ["http"]  # Handle HTTP traffic
    port = 80  # External port for HTTP

  [[services.ports]]
    handlers = ["tls", "http"]  # Handle HTTPS traffic
    port = 443  # External port for HTTPS