app = 'fastapi-book-project-0mw-6g'
primary_region = 'lhr'

[build]

[[services]]
  internal_port = 80  # Nginx listens on 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
